name: Vanilla Plasma China
id: plasma-china
vibversion: 1.1.0

stages:
- id: build
  base: ghcr.io/vanilla-kde/plasma:dev
  singlelayer: false
  labels:
    maintainer: FangcatChina
  args:
    DEBIAN_FRONTEND: noninteractive
  runs:
    commands:
      - echo 'APT::Install-Recommends "1";' > /etc/apt/apt.conf.d/01norecommends
  cleanup:
    - /var/cache/debconf
    - /var/cache/ldconfig
    - /var/cache/man
    - /var/log/*
  addincludes: true

  modules:
  - name: init-setup
    type: shell
    commands:
    - lpkg --unlock
    - apt update

  - name: cleanup
    type: shell
    commands:
    - apt autoremove -y
    - apt clean
    - lpkg --lock
