name: Vanilla KDE China
id: kde-china
vibversion: 1.1.0

stages:
- id: build
  base: ghcr.io/vanilla-kde/kde:dev
  singlelayer: false
  labels:
    maintainer: FangcatChina
  args:
    DEBIAN_FRONTEND: noninteractive
  runs:
    commands:
      - echo 'APT::Install-Recommends "1";' > /etc/apt/apt.conf.d/01norecommends
  cleanup:
    - /var/cache/debconf
    - /var/cache/ldconfig
    - /var/cache/man
    - /var/log/*
  addincludes: true

  modules:
  - name: init-setup
    type: shell
    commands:
    - lpkg --unlock
    - apt update

  - name: patch-flatpak-first-setup-remote
    type: shell
    commands:
      - flatpak remote-add --user --if-not-exists flathub https://mirror.sjtu.edu.cn/flathub/flathub.flatpakrepo
      - flatpak remote-modify --user flathub --url=https://mirrors.cernet.edu.cn/flathub

  - name: cleanup
    type: shell
    commands:
    - apt autoremove -y
    - apt clean
    - lpkg --lock
